version: '3'

services:
  api-solid-pg:
    image: postgres 
    container_name: api-solid-pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: api_solid
    ports:
      - 5432:5432